# Generated by Django 5.0.6 on 2024-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
